apiVersion: apps/v1
kind: Deployment
metadata: 
  name: server-deployment
spec:
  selector:
    matchLabels:
      app: server-deployment
  replicas: 1
  template:
    metadata:
      labels: 
        app: server-deployment
    spec:
      # restartPolicy: Never
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: server-container
        image: "server_app:lastest"
        imagePullPolicy: Never
        volumeMounts:
        - name: shared-data
          mountPath: /var/log/server_log/
        ports:
        - name: listen-port
          containerPort: 9999
          hostPort: 9999
        - name: ssh-port
          containerPort: 22
          hostPort: 15000
      - name: sshd-container
        image: "sshd:lastest"
        imagePullPolicy: Never
        volumeMounts:
        - name: shared-data
          mountPath: /var/log/server_log/
        ports:
        - name: ssh-port
          containerPort: 22
          hostPort: 15001
